/*
 * This source file was generated by the Gradle 'init' task
 */
package org.LoadBalancer;

public class Main {
    public static void main(String[] args) throws Exception {
        // Delegate to our reverse‐proxy’s main()
        RevProxyServer.main(args);
    }
}
